[package]
name = "user-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
bcrypt = "0.17.1"
rand = "0.9.2"
serde = "1.0.225"
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-async-std", "runtime-async-std-rustls"] }
tokio = "1.47.1"
